name = "QuartoTools"
uuid = "7b3f1b3e-36f4-49df-9651-0a56ec489f34"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
